[project]
name = "hackathon2-team1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Aris Miletis", email = "arismiletis@outlook.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
hackathon2-team1 = "hackathon2_team1:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
